baseURL = 'https://lukasvik.io/'
languageCode = 'en-us'
title = 'Lukas Vik'

# ------------------------------------------------------------------------------
# Theme settings
# ------------------------------------------------------------------------------
theme = "hugo-story"
disableKinds = ["taxonomy", "section"]

# ------------------------------------------------------------------------------
# Contact links
# ------------------------------------------------------------------------------
[[Params.social]]
name = "Linkedin"
icon = "brands fa-linkedin"
link = "https://www.linkedin.com/in/lukas-vik"

[[Params.social]]
name = "GitHub"
icon = "brands fa-github"
link = "https://github.com/LukasVik"

[[Params.social]]
name = "Email"
icon = "fa-envelope"
link = "mailto:lukas.vik.biz@gmail.com"

[[Params.social]]
name = "Telegram"
icon = "brands fa-telegram"
link = "https://telegram.me/lukasvik89"

[[Params.social]]
name = "YouTube"
icon = "brands fa-youtube"
link = "https://www.youtube.com/@lukasvik89"

# ------------------------------------------------------------------------------
# Open-source projects
# ------------------------------------------------------------------------------
[[Params.open_source]]
name = "hdl-modules"
website = "https://hdl-modules.com"
description = """
I am the author and maintainer of hdl-modules, a collection of reusable, high-quality,
peer-reviewed VHDL building blocks.
"""

[[Params.open_source]]
name = "hdl-registers"
website = "https://hdl-registers.com"
description = """
I am the author and maintainer of hdl-registers, an HDL register code generator fast enough
to run in real time.
"""

[[Params.open_source]]
name = "tsfpga"
website = "https://tsfpga.com"
description = """
I am the author and maintainer of tsfpga, a flexible and scalable development platform for
modern FPGA projects.
"""

# ------------------------------------------------------------------------------
# Professional experience
# ------------------------------------------------------------------------------
[[Params.job]]
title = "FPGA Engineer"
company_name = "IMC Trading"
start_year = "2025"
end_year = ""
location_city = "Sydney"
location_country = "Australia"
description = """
Developing custom FPGA-based financial trading solutions.
"""

[[Params.job]]
title = "Senior Staff Engineer in Digital Design"
company_name = "Sarcura"
start_year = "2024"
end_year = "2025"
location_city = "Vienna"
location_country = "Austria"
description = """
Responsible for digital design of a product that automates CAR-T cell manufacturing for cancer care.
I wrote the complete stack of FPGA (VHDL), embedded software (C++) and PC client (Python) from scratch in six months.
Including a custom TCP link for device configuration, status diagnostics, and data logging/visualization.
"""

[[Params.job]]
title = "Co-founder, FPGA expert"
company_name = "Truestream"
start_year = "2019"
end_year = "2023"
location_city = "Linköping"
location_country = "Sweden"
description = """
An FPGA design startup I founded with some friends.
I worked as an FPGA expert on some very advanced products with bleeding-edge high-speed design.
Example projects from these years:

<ul style="margin-top: -1em; margin-bottom: 1em;">
    <li>Lead developer for an FPGA-based ethernet switch</li>
    <li>Lead developer for an FPGA-based Hi-Fi audio product</li>
    <li>Lead developer for a video headend device</li>
    <li>Lead developer of custom FPGA IP</li>
</ul>

I also did a lot of embedded software and PC GUI development.
And, of course, a lot of other things that come with running a startup: finance, legal, sales, marketing, etc.
"""

[[Params.job]]
title = "Freelance Consultant"
company_name = "Blue Steel Engineering"
start_year = "2017"
end_year = "2019"
location_city = "Linköping"
location_country = "Sweden"
description = """
My one-man consulting company where I provided services in FPGA/software development.
Projects:

<ul style="margin-top: -1em">
    <li>Embedded software for the homing system of a next-generation underwater torpedo</li>
    <li>FPGA and embedded software for an industrial 3D camera, with focus on signal processing</li>
</ul>
"""

[[Params.job]]
title = "FPGA Developer"
company_name = "Autoliv Electronics"
start_year = "2014"
end_year = "2017"
location_city = "Linköping"
location_country = "Sweden"
description = """
Developing an FPGA-based image processing system for self-driving cars.
Apart from develpoment, I did team leading, pre-studies, CI, etc.
"""

# ------------------------------------------------------------------------------
# Publications
# ------------------------------------------------------------------------------
[[Params.publication]]
url = "https://www.linkedin.com/pulse/reliable-cdc-constraints-5-asynchronous-fifo-lukas-vik-snlgf"
title = "Reliable FPGA CDC constraints #5: Asynchronous FIFO"
year = 2024
type = "article"

[[Params.publication]]
url = "https://www.linkedin.com/pulse/reliable-cdc-constraints-4-build-tool-settings-lukas-vik-yknsc"
title = "Reliable FPGA CDC constraints #4: Build tool settings"
year = 2024
type = "article"

[[Params.publication]]
url = "https://www.linkedin.com/pulse/reliable-cdc-constraints-3-pulses-lukas-vik-31tif"
title = "Reliable FPGA CDC constraints #3: Pulses"
year = 2024
type = "article"

[[Params.publication]]
url = "https://www.linkedin.com/pulse/reliable-cdc-constraints-2-counters-fifos-lukas-vik-ist5c"
title = "Reliable FPGA CDC constraints #2: Counters and FIFOs"
year = 2024
type = "article"

[[Params.publication]]
url = "https://www.linkedin.com/pulse/reliable-cdc-constraints-1-lukas-vik-copcf"
title = "Reliable FPGA CDC constraints #1: The simple single-bit level CDC"
year = 2024
type = "article"

# Rendered as separator
[[Params.publication]]
url = ""

[[Params.publication]]
url = "https://www.linkedin.com/pulse/io-timing-constraints-fpgaasic-6-sink-synchronous-output-lukas-vik-yod6f"
title = "I/O timing constraints for FPGA/ASIC #6: Sink-synchronous output"
year = 2025
type = "article"

[[Params.publication]]
url = "https://www.linkedin.com/pulse/io-timing-constraints-fpgaasic-5-system-synchronous-output-lukas-vik-bv86f"
title = "I/O timing constraints for FPGA/ASIC #5: System-synchronous output"
year = 2025
type = "article"

[[Params.publication]]
url = "https://www.linkedin.com/pulse/io-timing-constraints-fpgaasic-4-source-synchronous-output-lukas-vik-fudxc"
title = "I/O timing constraints for FPGA/ASIC #4: Source-synchronous output"
year = 2025
type = "article"

[[Params.publication]]
url = "https://www.linkedin.com/pulse/io-timing-constraints-fpgaasic-3-sink-synchronous-input-lukas-vik-iuxuf"
title = "I/O timing constraints for FPGA/ASIC #3: Sink-synchronous input"
year = 2025
type = "article"

[[Params.publication]]
url = "https://www.linkedin.com/pulse/io-timing-constraints-fpgaasic-2-system-synchronous-input-lukas-vik-gpnkf"
title = "I/O timing constraints for FPGA/ASIC #2: System-synchronous input"
year = 2025
type = "article"

[[Params.publication]]
url = "https://www.linkedin.com/pulse/io-timing-constraints-fpgaasic-1-source-synchronous-input-lukas-vik-0xslf"
title = "I/O timing constraints for FPGA/ASIC #1: Source-synchronous input"
year = 2025
type = "article"

# Rendered as separator
[[Params.publication]]
url = ""

[[Params.publication]]
url = "https://www.linkedin.com/pulse/many-ways-mess-up-readyvalid-handshaking-lukas-vik-2mqdf"
title = "The many ways to mess up ready/valid handshaking"
year = 2024
type = "article"

[[Params.publication]]
url = "https://www.youtube.com/watch?v=AA-YJNMIDJw"
title = "Why is CDC so hard? Presentation at CERN"
year = 2024
type = "conference talk"

[[Params.publication]]
url = "https://youtu.be/kt4FGFKl5E0"
title = "Simulate FPGA design with Vivado simulation libraries"
year = 2024
type = "video tutorial"

# Rendered as separator
[[Params.publication]]
url = ""

[[Params.publication]]
url = "http://liu.diva-portal.org/smash/get/diva2:747961/FULLTEXT01.pdf"
title = "Real-time stereoscopic object tracking on FPGA using neural networks"
year = 2014
type = "master thesis"
